"""사용자 Repository 인터페이스"""
from abc import ABC, abstractmethod
from typing import Optional
from domain.entities.user import UserEntity


class UserRepository(ABC):
    @abstractmethod
    async def get_by_id(self, user_id: int) -> Optional[UserEntity]: ...
    @abstractmethod
    async def get_by_email(self, email: str) -> Optional[UserEntity]: ...
    @abstractmethod
    async def get_by_api_key(self, api_key: str) -> Optional[UserEntity]: ...
    @abstractmethod
    async def save(self, user: UserEntity) -> None: ...
    @abstractmethod
    async def create(self, email: str, password_hash: str, name: str,
                     phone: Optional[str] = None, company: Optional[str] = None) -> UserEntity: ...
    @abstractmethod
    async def update_credits(self, user_id: int, credits: int, credits_used: int) -> None: ...
    @abstractmethod
    async def update_last_login(self, user_id: int) -> None: ...
